### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Mindgibber** [truemedian/zfetch#12]
Running any example without an internet connection leads to a segmentation fault.

`Segmentation fault at address 0xaaaaaaaaaaaaaaba
/home/rc/zig/0.10.0-dev.1659+4dd65316b/files/lib/zig/std/mem/Allocator.zig:177:23: 0x23c740 in std.mem.Allocator.free (znettest)
    return self.vtable.free(self.ptr, buf, buf_align, ret_addr);
                      ^
/home/rc/zig/0.10.0-dev.1659+4dd65316b/files/lib/zig/std/heap/arena_allocator.zig:41:38: 0x254e4b in std.heap.arena_allocator.ArenaAllocator.deinit (znettest)
            self.child_allocator.free(node.data);
                                     ^
/home/rc/zig/0.10.0-dev.1659+4dd65316b/files/lib/zig/std/net.zig:734:33: 0x2549bb in std.net.getAddressList (znettest)
    errdefer result.arena.deinit();
                                ^
/home/rc/zig/0.10.0-dev.1659+4dd65316b/files/lib/zig/std/net.zig:686:36: 0x2544fb in std.net.tcpConnectToHost (znettest)
    const list = try getAddressList(allocator, name, port);
                                   ^
/home/rc/Projects/znettest/.zigmod/deps/git/github.com/truemedian/zfetch/src/connection.zig:76:52: 0x25407f in .zfetch.connection.Connection.rawConnect (znettest)
                return try std.net.tcpConnectToHost(allocator, options.hostname, real_port);
                                                   ^
/home/rc/Projects/znettest/.zigmod/deps/git/github.com/truemedian/zfetch/src/connection.zig:103:37: 0x2526d3 in .zfetch.connection.Connection.connect (znettest)
        conn.socket = try rawConnect(allocator, conn.options);
                                    ^
/home/rc/Projects/znettest/.zigmod/deps/git/github.com/truemedian/zfetch/src/request.zig:146:44: 0x24b533 in .zfetch.request.Request.init (znettest)
        req.socket = try Connection.connect(allocator, options);
                                           ^
/home/rc/Projects/znettest/src/main.zig:18:38: 0x245293 in main (znettest)
    var req = try zfetch.Request.init(allocator, "https://httpbin.org/get", null);
                                     ^
/home/rc/zig/0.10.0-dev.1659+4dd65316b/files/lib/zig/std/start.zig:574:37: 0x23f30f in std.start.callMain (znettest)
            const result = root.main() catch |err| {
                                    ^
/home/rc/zig/0.10.0-dev.1659+4dd65316b/files/lib/zig/std/start.zig:508:12: 0x22a1c7 in std.start.callMainWithArgs (znettest)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/rc/zig/0.10.0-dev.1659+4dd65316b/files/lib/zig/std/start.zig:418:17: 0x22949b in std.start.posixCallMainAndExit (znettest)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/home/rc/zig/0.10.0-dev.1659+4dd65316b/files/lib/zig/std/start.zig:331:5: 0x229337 in std.start._start (znettest)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
Aborted`

**Comment by truemedian** [comment]
Forgot to get back about this, but this is a zig bug. see: <https://github.com/ziglang/zig/issues/11358>
