### ISSUE TITLE
Follow HTTP 302 redirects automatically

### ISSUE THREAD

**Issue by theseyan** [truemedian/zfetch#13]
`zfetch` is a great library, just what I was looking for.
However, it doesn't seem to automatically follow 302 redirects (cannot download a GitHub release asset directly with link because GitHub does a 302 redirect first).
It would be nice if zfetch exposed an option to follow redirects (like cURL's FOLLOWLOCATION) or just did it by default so that manual implementation is not required.

**Comment by truemedian** [comment]
This was not feasible to do since zfetch only barely understood how connections worked.
