### ISSUE TITLE
Async error

### ISSUE THREAD

**Issue by kristoff-it** [truemedian/zfetch#4]
Example code which works in blocking mode but not in evented mode.

To test, you can run `ncat -lvnp 443 --ssl` ([ncat](https://nmap.org/ncat/) is like netcat but with ssl support).
In evented mode ncat doesn't show anything, meaning that the failure happens before we get to the HTTP stuff.

```zig
const std = @import("std");
const zfetch = @import("zfetch");

pub const io_mode = .evented;

pub fn main() !void {
    var allocator = std.heap.c_allocator;
    const path = "https://localhost/emoticons/v1/302432384/3.0";

    std.log.debug("emote url = ({s})", .{path});

    var headers = zfetch.Headers.init(allocator);
    defer headers.deinit();

    try headers.appendValue("Host", "static-cdn.jtvnw.net");
    try headers.appendValue("User-Agent", "Bork");
    try headers.appendValue("Accept", "*/*");

    var req = try zfetch.Request.init(allocator, path, null);
    defer req.deinit();

    try req.do(.GET, headers, null);

    if (req.status.code != 200) {
        std.log.err("emote request failed ({s})", .{path});
        return error.HttpError;
    }

    _ = try req.reader().readAllAlloc(allocator, 1024 * 100);
}
```

**Comment by wozeparrot** [comment]
This is probably due to https://github.com/ziglang/zig/issues/7593.

A possible fix is to do what `iguanaTLS` does in it's test cases which is to seed the `DefaultCsprng` using `std.os.getrandom` and passing that as the random implementation to `tls.client_connect`: https://github.com/nektro/iguanaTLS/blob/9a05f03681d5f273d0ce7447f0c7e729828ab8a2/src/main.zig#L1968-L1973.

**Comment by truemedian** [comment]
Wow, nice catch. For some reason Gimli's vectorized permute has a miscompilation on my machine so I've used Isaac64 instead.

However, with this workaround in place zfetch is now working in evented io.

**Comment by truemedian** [comment]
zfetch now works with evented io on macos and linux. I'm going to keep this issue open until evented io with std.net works on windows. The stdlib bug is filed as ziglang/zig#11247
