### ISSUE TITLE
deps.zig not present and errors if submoduling

### ISSUE THREAD

**Issue by JonSnowbd** [truemedian/zfetch#6]
https://github.com/truemedian/zfetch/blob/bae100ecec339738851e84dd699fd351d4cb9471/build.zig#L20

Importing is always done even if I'm not using the build function, causing it to error out with `deps.zig not found`

I just deleted the else branch right now, not sure how this is handled gracefully.

**Comment by truemedian** [comment]
Now that the stage1 compiler runs astcheck over the entire codebase regardless of use, I'll need to provide an empty deps.zig for it to quietly ignore.
